Repository shikosai33/shikosai33-web, pull requests merged in 2024-10, with the labels that each got.

#21 chore: 🔧 (`.github`) IssueとPRのテンプレートを追加した。 (#3)
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feat.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🔧 chore, 📅 重要度 high (最速実装最速レビュー)

#23 TailwindCSSにカラートークンの設定を追加した
  src/layouts/Layout.astro
  src/styles/colors.css
  tailwind.config.ts
Labels: 🔧 chore, 📅 重要度 high (最速実装最速レビュー)

#6 chore: 🔧 (`.vscode`) VSCode向けの設定の記述を移した (#4)
  .vscode/settings.json
  shikosai33-web.code-workspace
Labels: 🔧 chore, 📅 重要度 high (最速実装最速レビュー)

#28 chore: 🔧 (docker) docker 関連の設定ファイルを削除
  .devcontainer/devcontainer.json
  .dockerignore
  docker/Dockerfile.development
  docker/docker-compose.development.yaml
Labels: 🔧 chore, 📅 重要度 low (余裕があったら)

#27 chore: 🔧 (vscode) headwind がファイルの保存時に実行されるように修正 (26)
  .vscode/settings.json
Labels: 🔧 chore, 📅 重要度 high (最速実装最速レビュー)

#25 サークル, イベント, 場所のContent Collectionsのスキーマを追加した
  lefthook.yaml
  package.json
  src/content/circles/_images/club-season.jpg
  src/content/circles/club-season.md
  src/content/config.ts
  src/content/events/_images/PLUSHIE.png
  src/content/events/_images/gasaire-plankton.jpg
  src/content/events/gasaire-plankton.md
  src/content/events/plushie.md
  src/content/locations/indoor-stage.yml
  src/content/locations/seminar-room.yml
Labels: 🔧 chore, 📅 重要度 high (最速実装最速レビュー)

#33 chore: 🔧 (docker) docker に関連する設定ファイルを追加 (32)
  .devcontainer/devcontainer.json
  .gitignore
  docker/Dockerfile.development
  docker/docker-compose.development.yaml
Labels: 🔧 chore, 📅 重要度 high (最速実装最速レビュー)

#40 chore:アセットの差し替え
  src/assets/cover.png
  src/assets/cover_no_texts.png
  src/assets/poster.png
  src/assets/poster_no_texts.png
  src/assets/shikosai33.png
  src/assets/shikosai33_logo.png
Labels: 🍱 chore, 📅 重要度 high (最速実装最速レビュー)

#38 refactor: ♻️ (`<Layout>`) Google Fontsの読み込み用CSSをインライン化した。 (#37)
  bun.lockb
  package.json
  src/layouts/Layout.astro
  src/styles/global.css
Labels: ♻️ refactor, 📅 重要度 low (余裕があったら)

#36 CloudflareのAstroアダプタとOpengraphの設定を追加した
  astro.config.ts
  bun.lockb
  package.json
  public/opengraph-image.png
  src/layouts/Layout.astro
  src/pages/index.astro
Labels: 📦️ build, 🔧 chore, 📅 重要度 high (最速実装最速レビュー)

#19 feat:✨footerコンポーネントを実装した( #18 )
  src/assets/cover.png
  src/assets/cover_no_texts.png
  src/assets/kosen_logo.svg
  src/assets/poster.png
  src/assets/poster_no_texts.png
  src/assets/shikosai33.png
  src/assets/shikosai33_logo.png
  src/components/footer.astro
  src/pages/index.astro
Labels: ✨ feat

#31 feat:✨イラストカルーセルの実装( # 29 )
  bun.lockb
  package.json
  src/components/scripts/slideshow.tsx
  src/components/slideshow.astro
  src/pages/index.astro
Labels: 📅 重要度 medium (計画的に進める)

#46 イベントの情報を表示するカード`<EventCard>`を追加した
  bun.lockb
  package.json
  src/components/EventCard.astro
  src/components/EventStatus.astro
  src/utils/datetime/formatDateTimeRange.test.ts
  src/utils/datetime/formatDateTimeRange.ts
  tailwind.config.ts
Labels: ✨ feat, 📅 重要度 medium (計画的に進める)

#52 build: 📦️ Wranglerを導入した。 (#51)
  .gitignore
  .prototools
  biome.json
  bun.lockb
  package.json
  wrangler.toml
Labels: 🔧 chore, 📅 重要度 medium (計画的に進める)

#56 サークルの情報を表示するカード`<CircleCard>`を追加した
  src/components/CircleCard.astro
  src/utils/location/getLocationLocale.test.ts
  src/utils/location/getLocationLocale.ts
Labels: ✨ feat, 📅 重要度 medium (計画的に進める)

#60 `/event`を実装した
  src/components/footer.astro
  src/components/header.astro
  src/pages/event.astro
Labels: ✨ feat, 📅 重要度 medium (計画的に進める)

#68 chore: 🍱 Opengraphとメタデータを最新のものに更新した。 (#67)
  public/apple-icon.png
  public/favicon.png
  public/opengraph-image.png
  src/layouts/Layout.astro
Labels: 🍱 chore, 📅 重要度 medium (計画的に進める)

#65 feat: ✨ (`<StudentCard>`) 学生の情報を表示するカードを追加した。 (#58)
  src/components/StudentCard.astro
Labels: ✨ feat, 📅 重要度 medium (計画的に進める)

#75 `<Layout>`を実装した。
  src/assets/cover.png
  src/assets/cover_no_texts.png
  src/assets/kosen_logo.svg
  src/assets/poster.png
  src/assets/poster_no_texts.png
  src/assets/shikosai33_logo.png
  src/components/HeroSlideShow.astro
  src/components/footer.astro
  src/components/header.astro
  src/components/scripts/slideshow.tsx
  src/components/slideshow.astro
  src/layouts/Layout.astro
  src/pages/event.astro
  src/pages/index.astro
  src/utils/location/getLocationLocale.ts
Labels: ✨ feat, 📅 重要度 high (最速実装最速レビュー)

#81 ボタン風のリンク`<ButtonLink>`, 影と色付きのコンテナ`<ColoredContainer>`を実装した
  src/components/ButtonLink.astro
  src/components/ColoredContainer.astro
Labels: ♻️ refactor, 📅 重要度 high (最速実装最速レビュー)

#83 feat: ✨ (`/404`) 404 Not Foundページを追加した。 (#82)
  src/assets/404.png
  src/pages/404.astro
Labels: ✨ feat, 📅 重要度 low (余裕があったら)

#85 fix: 🐛 (`<ColoredContainer>`) 影が適用されない問題を修正した。 (#84)
  src/components/ColoredContainer.astro
Labels: 🐛 fix, 📅 重要度 medium (計画的に進める)

#87 外部URLの追記・画像の差し替え
  src/content/circles/2-1.md
  src/content/circles/2-5.md
  src/content/circles/3m2.md
  src/content/circles/fantasque.md
  src/content/circles/kokusai-kouryu.md
  src/content/circles/robot.md
  src/content/events/_images/nida-ira.jpg
  src/content/events/_images/nida-ira.png
  src/content/events/marks.md
  src/content/events/nida-ira.md
Labels: 🍱 chore, 📅 重要度 high (最速実装最速レビュー)

#70 feat: `/circle`を実装した(#69)
  src/components/footer.astro
  src/pages/circle.astro
Labels: ✨ feat, 📅 重要度 medium (計画的に進める)

#90 chore: 🔧 Astroの出力モードを`output: "hybrid"`に設定した (#89)
  astro.config.ts
Labels: 🔧 chore, 📅 重要度 high (最速実装最速レビュー)

#64 feat: `/event/{slug}`を実装した(#61)
  src/assets/kawaii_text_violet.png
  src/content/events/alpaca1.md
  src/content/events/alpaca2.md
  src/content/events/chuonikizu.md
  src/content/events/cosplay-show.md
  src/content/events/fireworks.md
  src/content/events/himitsu-bakuro.md
  src/content/events/id-lottery.md
  src/content/events/isador.md
  src/content/events/kintokisan.md
  src/content/events/kosensei-no-shucho.md
  src/content/events/nida-ira.md
  src/content/events/niowase.md
  src/content/events/osu-penguin1.md
  src/content/events/osu-penguin2.md
  src/content/events/plushie.md
  src/content/events/sasaki.md
  src/content/events/seki-tomohiro.md
  src/content/events/speed-eating.md
  src/content/events/stamp-rally.md
  src/content/events/syoten.md
  src/content/events/txit1.md
  src/content/events/txit2.md
  src/content/events/whats-in-the-box.md
  src/pages/event/[slug].astro
Labels: ✨ feat, 📅 重要度 medium (計画的に進める)

#76 43/theme intro
  src/assets/heisei-heart.png
  src/assets/heisei-tiara.png
  src/assets/shikosai33-anniversary-logo.png
  src/components/theme.astro
  src/pages/index.astro
Labels: 📅 重要度 medium (計画的に進める)

#97 再利用可能な見出し、サブ見出し、かわいいコンテナを実装した
  src/components/ColoredHeading.astro
  src/components/KawaiiContainer.astro
  src/components/SubHeading.astro
Labels: ✨ feat, ♻️ refactor, 📅 重要度 high (最速実装最速レビュー)

#95 feat: ✨ (`/event/[slug]`) Youtubeの動画の埋め込み表示機能を追加した (#94)
  src/content/events/d-c.md
  src/content/events/gasaire-plankton.md
  src/content/events/i-scream.md
  src/content/events/mmmmic.md
  src/content/events/plushie.md
  src/content/events/shichimi-mayonnaise.md
  src/content/events/yoacopi.md
  src/pages/event/[slug].astro
Labels: ✨ feat, 📅 重要度 medium (計画的に進める)

#93 検索ページ`/search`をPagefindを用いて実装した
  bun.lockb
  package.json
  src/components/header.astro
  src/layouts/Layout.astro
  src/pages/circle/[slug].astro
  src/pages/event/[slug].astro
  src/pages/search.astro
Labels: ✨ feat, 📅 重要度 low (余裕があったら)

#107 feat: ✨ (/event) ｢トップページへ戻る｣ボタンを追加した (#100)
  src/pages/event.astro
Labels: ✨ feat, 📅 重要度 medium (計画的に進める)

#106 ダークモードに対応させた
  src/components/HeroSlideShow.astro
  src/components/footer.astro
  src/layouts/Layout.astro
  src/pages/circle/[slug].astro
  src/styles/colors.css
Labels: ✨ feat, 📅 重要度 low (余裕があったら)

#112 chore: 🍱 委員の集合写真を追加 (#108)
  src/assets/staff.jpg
Labels: 🍱 chore, 📅 重要度 high (最速実装最速レビュー)

#117 feat: ✨ (/circle) ButtonLinkによる｢トップページに戻る｣ボタンを追加 (#99)
  src/components/ButtonLink.astro
  src/pages/circle.astro
Labels: ✨ feat, 📅 重要度 medium (計画的に進める)

#119 chore: 🍱 (`outdoor_tents.svg`) サークル名を修正 (118)
  src/content/locations/_maps/outdoor_tents.svg
Labels: 🍱 chore, 📅 重要度 high (最速実装最速レビュー)

#114 feat: ✨ (`<AccessPanel>`) `<AccessPanel>`を実装した (#113)
  src/components/AccessPanel.astro
Labels: ✨ feat, 📅 重要度 medium (計画的に進める)

#116 feat: ✨ (`<StaffPanel>`) StaffPanelを実装した (#115)
  src/components/StaffPanel.astro
Labels: ✨ feat, 📅 重要度 medium (計画的に進める)

#101 feat: ✨ (/access) 情報を正式なものに更新した
  src/assets/access_bus.png
  src/assets/access_taxi.png
  src/components/footer.astro
  src/components/header.astro
  src/content/locations/_maps/school_map.svg
  src/pages/access.astro
Labels: ✨ feat, 📅 重要度 medium (計画的に進める)

#110 フッターに色のテーマを指定できるセレクタを追加した
  bun.lockb
  package.json
  src/components/UIThemeSelect.tsx
  src/components/footer.astro
  src/components/header.astro
  src/layouts/Layout.astro
Labels: ✨ feat, 📅 重要度 low (余裕があったら)

#121 style: 💄 (`<Theme>`) ちゃぁみぃ！の文字がコンテナに収まるように修正した。 (#120)
  src/components/theme.astro
Labels: 🐛 fix, 📅 重要度 high (最速実装最速レビュー)

#124 fix: 🐛 (`<Layout>`) View Transitionのページ遷移時にちらつきなく`.dark`が適用されるよう購読イベントを変更した。 (#123)
  src/layouts/Layout.astro
Labels: 🐛 fix, 📅 重要度 medium (計画的に進める)

#125 `/enquete`を実装した
  src/components/footer.astro
  src/pages/enquete.astro
Labels: ✨ feat, 📅 重要度 medium (計画的に進める)

#129 fix: 🐛 (`<Layout>`) 子要素で`w-full`が`md:`以上でも正しく動作するよう幅指定を修正した。 (#128)
  src/layouts/Layout.astro
Labels: 🐛 fix, 📅 重要度 high (最速実装最速レビュー)

#131 `<EventPanel>`を実装した
  src/components/EventPanel.astro
  src/components/HeroSlideShow.astro
Labels: ✨ feat, 📅 重要度 medium (計画的に進める)

#135 fix: 🐞 (`<EventPanel>`) フォントサイズを修正 (#134)
  src/components/EventPanel.astro
Labels: 🐞 fix, 📅 重要度 high (最速実装最速レビュー)

#133 fix: 🐞 (`/access`) paddingを無視して上まで広がるよう修正 (#132)
  src/pages/access.astro
Labels: 🐞 fix, 📅 重要度 high (最速実装最速レビュー)

#127 `<CirclePanel>`を実装した
  src/components/PreviewCircle.astro
  src/pages/index.astro
Labels: 📅 重要度 medium (計画的に進める)

#136 130/add panels to root
  src/components/AccessPanel.astro
  src/components/EventPanel.astro
  src/components/PreviewCircle.astro
  src/pages/index.astro
Labels: ✨ feat, 📅 重要度 medium (計画的に進める)

#137 `/root`のダウンロードボタンを実装した
  src/layouts/Layout.astro
Labels: 📅 重要度 high (最速実装最速レビュー)

#91 スタッフページの実装
  src/pages/staff.astro
Labels: ✨ feat, 📅 重要度 medium (計画的に進める)

#141 chore: 🍱 (/content/events/plushie.md) PLUSHIEのライブ配信リンクを正式なものに更新 (140)
  src/content/events/plushie.md
Labels: 🍱 chore, 📅 重要度 high (最速実装最速レビュー)

#142 fix: 🐛 (/content/events/plushie.md) YouTubeのリンクを、`v=`から始まるものに変更した (#…
  src/content/events/plushie.md
Labels: 🐛 fix, 📅 重要度 high (最速実装最速レビュー)
